### ISSUE TITLE
Server/lib/app.js whats with the async-await

### ISSUE THREAD

**Issue by axmad22** [weareopensource/meanjs-2#60]
Thanks for taking up the task to update Mean.js for Angular2.Whats with the app.js its using (Let, async, await), is this es6 or typescript and what transpiles this file to JS. Am using webstorm its showing them as errors

**Comment by farhatmo** [comment]
Hello @axmad22,

Yes it's ES6 . We think also to migrate the nodeJs server in Typescript. 
Maybe with Node V8.0.0 (come with support of async/await) you will not have the issue.
